locale                   : "en-US"
title                    : "test"
title_separator          : "-"
subtitle                 : test
name                     : "Your Name"
description              : "An amazing website."
url                      : "https://clikgw.github.io/Test2/"
baseurl                  : ""
