# Site Settings
locale                   : "en-US"
title                    : "Site Title"
title_separator          : "-"
subtitle                 : ""
name                     : "Your Name"
description              : "An amazing website."
url                      : "https://clikgw.github.io/Test2/"
baseurl                  : ""
